//
//  Constants.swift
//  Aldrete & Asociados
//
//  Created by Sandeep Kumar on 24/06/19.
//  Copyright © 2019 Code-Brew Labs. All rights reserved.
//

import UIKit

struct Height {
  static var MasterSection: CGFloat = 56.0
  static var ContactCell: CGFloat = 48.0
  static var FilterCell: CGFloat = 44.0
  static var DetailSection: CGFloat = 88.0
  static var MeetingPPTCell: CGFloat = 96.0
  static var MeetingLocationCell: CGFloat = UITableView.automaticDimension
  static var MeetingDateTimeCell: CGFloat = 56.0
  static var MeetingCalendarCell: CGFloat = 56.0
  static var FormCell: CGFloat = 144.0
  static var FormSectionView: CGFloat = 40.0
  static var FormKeyMenCell: CGFloat = 208.0
  static var FormAddFooterView: CGFloat = 48.0
  static var AddChildDependentSectionView: CGFloat = 184.0
  static var KeyMenChildDependentSectionView: CGFloat = 264.0
  static var ChildDependentCell: CGFloat = 64.0
  static var KeymenChildDependentCell: CGFloat = 90.0
  static var ContactDetailCell: CGFloat = 76.0
}


enum VCLiteral: String {
    
    case FILTER = "FILTER"
    case ALL_CONTACTS = "ALL_CONTACTS"
    case PF_SECTION_CONTACT_INFORMATION = "PF_SECTION_CONTACT_INFORMATION"
    case PF_SECTION_CONTACT_INFORMATION_F1 = "PF_SECTION_CONTACT_INFORMATION_F1"
    case PF_SECTION_CONTACT_INFORMATION_F2 = "PF_SECTION_CONTACT_INFORMATION_F2"
    case PF_SECTION_CONTACT_INFORMATION_F3 = "PF_SECTION_CONTACT_INFORMATION_F3"
    case PF_SECTION_PERSONAL_INFORMATION = "PF_SECTION_PERSONAL_INFORMATION"
    case PF_SECTION_PERSONAL_INFORMATION_F1 = "PF_SECTION_PERSONAL_INFORMATION_F1"
    case PF_SECTION_PERSONAL_INFORMATION_F2 = "PF_SECTION_PERSONAL_INFORMATION_F2"
    case PF_SECTION_PERSONAL_INFORMATION_F3 = "PF_SECTION_PERSONAL_INFORMATION_F3"
    case PF_SECTION_CHILDREN_DEPENDENTS = "PF_SECTION_CHILDREN_DEPENDENTS"
    case PF_SECTION_CHILDREN_DEPENDENTS_F1 = "PF_SECTION_CHILDREN_DEPENDENTS_F1"
    case PF_SECTION_CHILDREN_DEPENDENTS_F2 = "PF_SECTION_CHILDREN_DEPENDENTS_F2"
    case PF_SECTION_CHILDREN_DEPENDENTS_ADD_TITLE = "PF_SECTION_CHILDREN_DEPENDENTS_ADD_TITLE"
    case PF_SECTION_FINANCIAL_DATA = "PF_SECTION_FINANCIAL_DATA"
    case PF_SECTION_FINANCIAL_DATA_F01 = "PF_SECTION_FINANCIAL_DATA_F01"
    case PF_SECTION_FINANCIAL_DATA_F02 = "PF_SECTION_FINANCIAL_DATA_F02"
    case PF_SECTION_FINANCIAL_DATA_F03 = "PF_SECTION_FINANCIAL_DATA_F03"
    case PF_SECTION_FINANCIAL_DATA_F04 = "PF_SECTION_FINANCIAL_DATA_F04"
    case PF_SECTION_FINANCIAL_DATA_F05 = "PF_SECTION_FINANCIAL_DATA_F05"
    case PF_SECTION_FINANCIAL_DATA_F06 = "PF_SECTION_FINANCIAL_DATA_F06"
    case PF_SECTION_FINANCIAL_DATA_F07 = "PF_SECTION_FINANCIAL_DATA_F07"
    case PF_SECTION_FINANCIAL_DATA_F08 = "PF_SECTION_FINANCIAL_DATA_F08"
    case PF_SECTION_FINANCIAL_DATA_F09 = "PF_SECTION_FINANCIAL_DATA_F09"
    case PF_SECTION_FINANCIAL_DATA_F10 = "PF_SECTION_FINANCIAL_DATA_F10"
    case PF_SECTION_FINANCIAL_DATA_F11 = "PF_SECTION_FINANCIAL_DATA_F11"
    case PF_SECTION_FINANCIAL_DATA_F12 = "PF_SECTION_FINANCIAL_DATA_F12"
    case PF_SECTION_FINANCIAL_DATA_F13 = "PF_SECTION_FINANCIAL_DATA_F13"
    case PF_SECTION_FINANCIAL_DATA_F14 = "PF_SECTION_FINANCIAL_DATA_F14"
    case PF_SECTION_FINANCIAL_DATA_F15 = "PF_SECTION_FINANCIAL_DATA_F15"
    case PF_SECTION_FINANCIAL_DATA_F16 = "PF_SECTION_FINANCIAL_DATA_F16"
    case PF_SECTION_FINANCIAL_DATA_F17 = "PF_SECTION_FINANCIAL_DATA_F17"
    case PF_SECTION_FINANCIAL_DATA_F18 = "PF_SECTION_FINANCIAL_DATA_F18"
    case PF_SECTION_FINANCIAL_DATA_F19 = "PF_SECTION_FINANCIAL_DATA_F19"
    case PF_SECTION_FINANCIAL_DATA_F20 = "PF_SECTION_FINANCIAL_DATA_F20"
    case PF_SECTION_FINANCIAL_DATA_F21 = "PF_SECTION_FINANCIAL_DATA_F21"
    case PF_SECTION_FINANCIAL_DATA_F22 = "PF_SECTION_FINANCIAL_DATA_F22"
    case PF_SECTION_FINANCIAL_DATA_F23 = "PF_SECTION_FINANCIAL_DATA_F23"
    case PF_SECTION_FINANCIAL_DATA_F24 = "PF_SECTION_FINANCIAL_DATA_F24"
    case PF_SECTION_FINANCIAL_DATA_F25 = "PF_SECTION_FINANCIAL_DATA_F25"
    case PF_SECTION_FINANCIAL_DATA_F26 = "PF_SECTION_FINANCIAL_DATA_F26"
    case PF_SECTION_FINANCIAL_DATA_F27 = "PF_SECTION_FINANCIAL_DATA_F27"
    case PF_SECTION_FINANCIAL_DATA_F28 = "PF_SECTION_FINANCIAL_DATA_F28"
    case PF_SECTION_FINANCIAL_DATA_F29 = "PF_SECTION_FINANCIAL_DATA_F29"
    
    
    case CF_SEC_CONTACT_INFO = "CF_SEC_CONTACT_INFO"
    case CF_SEC_CONTACT_INFO_F1 = "CF_SEC_CONTACT_INFO_F1"
    case CF_SEC_CONTACT_INFO_F2 = "CF_SEC_CONTACT_INFO_F2"
    case CF_SEC_CONTACT_INFO_F3 = "CF_SEC_CONTACT_INFO_F3"
    case CF_SEC_PERSONAL_INFO = "CF_SEC_PERSONAL_INFO"
    case CF_SEC_PERSONAL_INFO_F1 = "CF_SEC_PERSONAL_INFO_F1"
    case CF_SEC_PERSONAL_INFO_F2 = "CF_SEC_PERSONAL_INFO_F2"
    case CF_SEC_KEY_MEN = "CF_SEC_KEY_MEN"
    case CF_SEC_KEY_MEN_F1 = "CF_SEC_KEY_MEN_F1"
    case CF_SEC_KEY_MEN_F2 = "CF_SEC_KEY_MEN_F2"
    case CF_SEC_KEY_MEN_F3 = "CF_SEC_KEY_MEN_F3"
    case CF_SEC_KEY_MEN_F4 = "CF_SEC_KEY_MEN_F4"
    case CF_SEC_KEY_MEN_F5 = "CF_SEC_KEY_MEN_F5"
    case CF_SEC_KEY_MEN_F6 = "CF_SEC_KEY_MEN_F6"
    case CF_SEC_KEY_MEN_BTN_ADD = "CF_SEC_KEY_MEN_BTN_ADD"
    case CF_SEC_DATE_OF_MEETING_F1 = "CF_SEC_DATE_OF_MEETING_F1"
    case CF_PROTECTION_ONLY = "CF_PROTECTION_ONLY"
    case CF_SAVING_FUND = "CF_SAVING_FUND";
    
    
    case FORM_PERSONAL_TITLE = "FORM_PERSONAL_TITLE"
    case FORM_COMPANY_TITLE = "FORM_COMPANY_TITLE"
    case FORM_CONFERENCE_TITLE = "FORM_CONFERENCE_TITLE"
    case FORM_ADD_MEETING = "FORM_ADD_MEETING"
    case UPLOAD_PRESENTATION = "UPLOAD_PRESENTATION"
    case RESCHEDULE = "RESCHEDULE"

    
    //Personal Form Validation Message
    case VD_PF_SECTION_CONTACT_INFORMATION_F1 = "VD_PF_SECTION_CONTACT_INFORMATION_F1"
    case VD_PF_SECTION_CONTACT_INFORMATION_F2 = "VD_PF_SECTION_CONTACT_INFORMATION_F2"
    case VD_PF_SECTION_CONTACT_INFORMATION_F3 = "VD_PF_SECTION_CONTACT_INFORMATION_F3"
    case VD_PF_SECTION_PERSONAL_INFORMATION_F1 = "VD_PF_SECTION_PERSONAL_INFORMATION_F1"
    case VD_PF_SECTION_PERSONAL_INFORMATION_F2 = "VD_PF_SECTION_PERSONAL_INFORMATION_F2"
    case VD_PF_SECTION_PERSONAL_INFORMATION_F3 = "VD_PF_SECTION_PERSONAL_INFORMATION_F3"
    case VD_PF_SECTION_CHILDREN_DEPENDENTS_F1 = "VD_PF_SECTION_CHILDREN_DEPENDENTS_F1"
    case VD_PF_SECTION_CHILDREN_DEPENDENTS_F2 = "VD_PF_SECTION_CHILDREN_DEPENDENTS_F2"
    case VD_PF_SECTION_FINANCIAL_DATA_F01 = "VD_PF_SECTION_FINANCIAL_DATA_F01"
    case VD_PF_SECTION_FINANCIAL_DATA_F02 = "VD_PF_SECTION_FINANCIAL_DATA_F02"
    case VD_PF_SECTION_FINANCIAL_DATA_F03 = "VD_PF_SECTION_FINANCIAL_DATA_F03"
    case VD_PF_SECTION_FINANCIAL_DATA_F04 = "VD_PF_SECTION_FINANCIAL_DATA_F04"
    case VD_PF_SECTION_FINANCIAL_DATA_F05 = "VD_PF_SECTION_FINANCIAL_DATA_F05"
    case VD_PF_SECTION_FINANCIAL_DATA_F06 = "VD_PF_SECTION_FINANCIAL_DATA_F06"
    case VD_PF_SECTION_FINANCIAL_DATA_F07 = "VD_PF_SECTION_FINANCIAL_DATA_F07"
    case VD_PF_SECTION_FINANCIAL_DATA_F08 = "VD_PF_SECTION_FINANCIAL_DATA_F08"
    case VD_PF_SECTION_FINANCIAL_DATA_F09 = "VD_PF_SECTION_FINANCIAL_DATA_F09"
    case VD_PF_SECTION_FINANCIAL_DATA_F10 = "VD_PF_SECTION_FINANCIAL_DATA_F10"
    case VD_PF_SECTION_FINANCIAL_DATA_F11 = "VD_PF_SECTION_FINANCIAL_DATA_F11"
    case VD_PF_SECTION_FINANCIAL_DATA_F12 = "VD_PF_SECTION_FINANCIAL_DATA_F12"
    case VD_PF_SECTION_FINANCIAL_DATA_F13 = "VD_PF_SECTION_FINANCIAL_DATA_F13"
    case VD_PF_SECTION_FINANCIAL_DATA_F14 = "VD_PF_SECTION_FINANCIAL_DATA_F14"
    case VD_PF_SECTION_FINANCIAL_DATA_F15 = "VD_PF_SECTION_FINANCIAL_DATA_F15"
    case VD_PF_SECTION_FINANCIAL_DATA_F16 = "VD_PF_SECTION_FINANCIAL_DATA_F16"
    case VD_PF_SECTION_FINANCIAL_DATA_F17 = "VD_PF_SECTION_FINANCIAL_DATA_F17"
    case VD_PF_SECTION_FINANCIAL_DATA_F18 = "VD_PF_SECTION_FINANCIAL_DATA_F18"
    case VD_PF_SECTION_FINANCIAL_DATA_F19 = "VD_PF_SECTION_FINANCIAL_DATA_F19"
    case VD_PF_SECTION_FINANCIAL_DATA_F20 = "VD_PF_SECTION_FINANCIAL_DATA_F20"
    case VD_PF_SECTION_FINANCIAL_DATA_F21 = "VD_PF_SECTION_FINANCIAL_DATA_F21"
    case VD_PF_SECTION_FINANCIAL_DATA_F22 = "VD_PF_SECTION_FINANCIAL_DATA_F22"
    case VD_PF_SECTION_FINANCIAL_DATA_F23 = "VD_PF_SECTION_FINANCIAL_DATA_F23"
    case VD_PF_SECTION_FINANCIAL_DATA_F24 = "VD_PF_SECTION_FINANCIAL_DATA_F24"
    case VD_PF_SECTION_FINANCIAL_DATA_F25 = "VD_PF_SECTION_FINANCIAL_DATA_F25"
    case VD_PF_SECTION_FINANCIAL_DATA_F26 = "VD_PF_SECTION_FINANCIAL_DATA_F26"
    case VD_PF_SECTION_FINANCIAL_DATA_F27 = "VD_PF_SECTION_FINANCIAL_DATA_F27"
    case VD_PF_SECTION_FINANCIAL_DATA_F28 = "VD_PF_SECTION_FINANCIAL_DATA_F28"
    case VD_PF_SECTION_FINANCIAL_DATA_F29 = "VD_PF_SECTION_FINANCIAL_DATA_F29"
    
    case VD_PF_SEC_CONTACT_INFO_CORRECT_EMAIL = "VD_PF_SEC_CONTACT_INFO_CORRECT_EMAIL"
    case VD_PF_SEC_CONTACT_INFO_CORRECT_WHATSAPP_NUMBER = "VD_PF_SEC_CONTACT_INFO_CORRECT_WHATSAPP_NUMBER"
    

    //Validation Company Form Table section and fields
    case VD_CF_SEC_CONTACT_INFO_F1 = "VD_CF_SEC_CONTACT_INFO_F1"
    case VD_CF_SEC_CONTACT_INFO_F2 = "VD_CF_SEC_CONTACT_INFO_F2"
    case VD_CF_SEC_CONTACT_INFO_F3 = "VD_CF_SEC_CONTACT_INFO_F3"
    case VD_CF_SEC_PERSONAL_INFO_F1 = "VD_CF_SEC_PERSONAL_INFO_F1"
    case VD_CF_SEC_PERSONAL_INFO_F2 = "VD_CF_SEC_PERSONAL_INFO_F2"
    case VD_CF_SEC_KEY_MEN_F1 = "VD_CF_SEC_KEY_MEN_F1"
    case VD_CF_SEC_KEY_MEN_F2 = "VD_CF_SEC_KEY_MEN_F2"
    case VD_CF_SEC_KEY_MEN_F3 = "VD_CF_SEC_KEY_MEN_F3"
    case VD_CF_SEC_KEY_MEN_F4 = "VD_CF_SEC_KEY_MEN_F4"
    case VD_CF_SEC_KEY_MEN_F5 = "VD_CF_SEC_KEY_MEN_F5"
    case VD_CF_SEC_KEY_MEN_F6 = "VD_CF_SEC_KEY_MEN_F6"
    case VD_CF_SEC_DATE_OF_MEETING_F1 = "VD_CF_SEC_DATE_OF_MEETING_F1"
    case VD_CF_SEC_CONTACT_INFO_CORRECT_EMAIL = "VD_CF_SEC_CONTACT_INFO_CORRECT_EMAIL"
    case VD_CF_SEC_CONTACT_INFO_CORRECT_WHATSAPP_NUMBER = "VD_CF_SEC_CONTACT_INFO_CORRECT_WHATSAPP_NUMBER"
    case VD_CF_SEC_CONTACT_VALID_AMOUNT = "VD_CF_SEC_CONTACT_VALID_AMOUNT"
    case VD_CF_SEC_CONTACT_VALID_DEFFERED_COMPENSATION = "VD_CF_SEC_CONTACT_VALID_DEFFERED_COMPENSATION"
    case VD_CF_KEY_MEN_VALID_SHARE_PERCENTAGE_OF_MEMBER = "VD_CF_KEY_MEN_VALID_SHARE_PERCENTAGE_OF_MEMBER"
    case VD_CF_EMAIL_ALREADY_EXIST = "VD_CF_EMAIL_ALREADY_EXIST"
    case VD_CF_NUMBER_ALREADY_EXIST = "VD_CF_NUMBER_ALREADY_EXIST"
    case VD_CF_DATA_SAVED_SUCCESSFULLY = "VD_CF_DATA_SAVED_SUCCESSFULLY"
    case VD_CF_SUCCESS = "VD_CF_SUCCESS"
    case VD_MEETING_MEETING_NAME = "VD_MEETING_MEETING_NAME"
    case VD_MEETING_MEETING_START_TIME = "VD_MEETING_MEETING_START_TIME"
    case VD_MEETING_MEETING_END_TIME = "VD_MEETING_MEETING_END_TIME"
    case VD_MEETING_MEETING_END_TIME_GREATER = "VD_MEETING_MEETING_END_TIME_GREATER"
    case VD_MEETING_DATE = "VD_MEETING_DATE"
    case VD_MEETING_LOCATION = "VD_MEETING_LOCATION"
    case VD_MEETING_PRESENTATION = "VD_MEETING_PRESENTATION"
    case VD_CONTACT_TYPE = "VD_CONTACT_TYPE"
    case VD_CONTACT_NUMBER = "VD_CONTACT_NUMBER"
    case VD_PF_SECTION_FINANCIAL_DATA_ONLY_NUMBER = "VD_PF_SECTION_FINANCIAL_DATA_ONLY_NUMBER"
    case VD_PF_SECTION_FINANCIAL_DATA_F07_NUMBER_ONLY = "VD_PF_SECTION_FINANCIAL_DATA_F07_NUMBER_ONLY"
    case VD_PF_SECTION_FINANCIAL_DATA_F14_NUMBER_ONLY = "VD_PF_SECTION_FINANCIAL_DATA_F14_NUMBER_ONLY"
    case ADD_MEETING = "ADD_MEETING"
    case EDIT_STATUS = "EDIT_STATUS"
    case EDIT_MAIN = "EDIT_MAIN"
    case DELETE_CONTACT = "DELETE_CONTACT"
    case VD_ARE_YOU_SURE_TO_DELETE = "VD_ARE_YOU_SURE_TO_DELETE"
    case DELETE_MEETING = "DELETE_MEETING"
 
    case ALL = "ALL"
    case WARM = "WARM"
    case HOT = "HOT"
    case COLD = "COLD"
    
    static var allValues = [VCLiteral.ADD_MEETING, .EDIT_STATUS, .EDIT_MAIN, .DELETE_CONTACT]
    static var statusVAlues = [VCLiteral.WARM, VCLiteral.HOT, VCLiteral.COLD]
    static var allStatusValues = [VCLiteral.ALL,VCLiteral.WARM, VCLiteral.HOT, VCLiteral.COLD]
    
    static var allHomeValues = [VCLiteral.UPLOAD_PRESENTATION, .RESCHEDULE]
    
    var localized: String {
        return NSLocalizedString(self.rawValue, comment: "")
    }
}



